'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mostrar_tablas_Result1
    Public Property Cedula As String
    Public Property Diagnostico As String
    Public Property Medicamento_Administrado As String
    Public Property Medicamento_Recetado As String
    Public Property Sangre As String
    Public Property Orina As String
    Public Property Sintomas As String

End Class
