'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BdCentroMedicoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BdCentroMedicoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property TbChequeoExamanes() As DbSet(Of TbChequeoExamanes)
    Public Overridable Property TbChequeoMedicamentos() As DbSet(Of TbChequeoMedicamentos)
    Public Overridable Property TbConsultaMedica() As DbSet(Of TbConsultaMedica)
    Public Overridable Property TbEnfermedad() As DbSet(Of TbEnfermedad)
    Public Overridable Property TbEspecialidad() As DbSet(Of TbEspecialidad)
    Public Overridable Property TbFamiliarPaciente() As DbSet(Of TbFamiliarPaciente)
    Public Overridable Property TbMedicamento() As DbSet(Of TbMedicamento)
    Public Overridable Property TbPersona() As DbSet(Of TbPersona)
    Public Overridable Property TbPersonalInterno() As DbSet(Of TbPersonalInterno)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TbPaciente() As DbSet(Of TbPaciente)
    Public Overridable Property TbCita() As DbSet(Of TbCita)

End Class
