'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TbChequeoMedicamentos
    Public Property IdChequeoMed As Integer
    Public Property CedulaP As String
    Public Property MedicamentoAdm As Integer
    Public Property MedicamentoRecetado As Integer

    Public Overridable Property TbMedicamento As TbMedicamento
    Public Overridable Property TbMedicamento1 As TbMedicamento
    Public Overridable Property TbConsultaMedica As ICollection(Of TbConsultaMedica) = New HashSet(Of TbConsultaMedica)

End Class
