'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TbFamiliarPaciente
    Public Property IdFamiliarP As Integer
    Public Property CedulaPaciente As String
    Public Property Parentesco As String
    Public Property NombreCompleto As String
    Public Property TelefonoFamiliar As String
    Public Property Direccion As String


End Class
