'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TbMedicamento
    Public Property IdMedicamento As Integer
    Public Property Medicamento As String

    Public Overridable Property TbChequeoMedicamentos As ICollection(Of TbChequeoMedicamentos) = New HashSet(Of TbChequeoMedicamentos)
    Public Overridable Property TbChequeoMedicamentos1 As ICollection(Of TbChequeoMedicamentos) = New HashSet(Of TbChequeoMedicamentos)

End Class
