'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TbPaciente
    Public Property IdPaciente As Integer
    Public Property CedulaPersona As String
    Public Property Peso As String
    Public Property Altura As String
    Public Property TipoSangre As String
    Public Property ContactoPaciente As Integer
    Public Property Sintomas As String
    Public Property MedicamentoAlergico As String

End Class
